version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Rozitek123@#
      - POSTGRES_DB=wms
    volumes:
      - ./data:/var/lib/postgresql/data
