# Use the official Node.js 14 image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the entire project to the working directory
COPY . .

# Build the Next.js app
RUN npm run build

# Expose the desired port (e.g., 3000) for the Next.js app
EXPOSE 3000

# Set the command to start the Next.js app
CMD ["npm", "run", "start"]