# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Pull request validation in Prostech.WMS.Website"

on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "Prostech.WMS.Website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Prostech.WMS.Website

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "Prostech.WMS.Website/package.json"
      - run: npm ci
      - run: npm run build --if-present
