name: 'Pull request validation in Prostech.WMS.API'

on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "Prostech.WMS.API/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: Prostech.WMS.API/Prostech.WMS.API
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
